### ISSUE TITLE
Hamburger menu contents need to be developed

### ISSUE THREAD

**Issue by mysterism** [tymsai/marmoym-design#14]
#14 My말모음, 사용자 의견, 도음말 등의 페이지 제작해야함.

**Comment by eldenpark** [comment]
@mysterism 이 이슈는 hamburger menu에 어떤 항목이 들어갈지 결정하는 것과 관련하는 것이죠? 항목이 결정되면 각 화면 Draft 제작 작업들은 서로 다른 이슈를 생성하여 착수해주세요~

**Comment by eldenpark** [comment]
Contents in 'Hamburger menu'*
This menu actually needs to be named properly, though.

- [ ] My Marmoym (or Account)
- [ ] Feedbacks
- [ ] Help
- [ ] ...

**Comment by mysterism** [comment]
던.
