### ISSUE TITLE
**MAJOR CHANGE** Term Entry shall display one definition.

### ISSUE THREAD

**Issue by mysterism** [tymsai/marmoym-design#22]
FYI

Original view - 
Term Entry would display multiple definitions: uploaded by random users, in numerical order w/o any fixed rule.

Updated view - 
On the Home screen, Term Entry will display definition; which has received the most up-votes from users.

On the searched screen(search result page), the most-voted definition will be displayed on the very top and will be followed by other definitions in due order of votes.

Please refer to "Urban Dictionary" for further understanding.

**Comment by eldenpark** [comment]
@mysterism You can also use the terms like 'as-is' (현상태) and 'to-be' (수정 후).

**Comment by eldenpark** [comment]
Done
