### ISSUE TITLE
Add part_of_speech on every term

### ISSUE THREAD

**Issue by mysterism** [tymsai/marmoym-design#29]
모든 term에 품사부분 추가.

term register시에 한글기준 최대 28자 등록가능하게 끔.
(최대 등록가능 글자 추후 논의필요)

@enginehenryed

**Comment by mysterism** [comment]
done

**Comment by eldenpark** [comment]
@mysterism 이 이슈 후에 추적해주세요.
해상도 다른 장치들 2-3개 샘플잡아서 확인해보면 좋을 것 같아요~
